### ISSUE TITLE
ValueError: GraphDef cannot be larger than 2GB.

### ISSUE THREAD

**Issue by vladimirtelepov** [spcl/ncc#23]
Hello, i run train_task_classifyapp.py to learn model myself, its differ only in last dense layer: i removed sigmoid activation function. Train was failed on last batch as i understand, but i cant unsderstand why.
Attached log:

 Tensor("l2_normalize:0", shape=(8565, 200), dtype=float32)

--- Initializing model...
        built Keras model

--- Training model...
Epoch 1/50
2436/2437 [============================>.] - ETA: 8s - loss: 8.2014 - acc: 0.0107 Traceback (most recent call last):
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "train_task_classifyapp.py", line 152, in __getitem__
    emb_x = tf.nn.embedding_lookup(self.emb, x).eval(session=self.sess)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 656, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5016, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1310, in _run_fn
    self._extend_graph()
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1353, in _extend_graph
    from_version=self._current_version, add_shapes=self._add_shapes)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3094, in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_task_classifyapp.py", line 572, in <module>
    app.run(switch)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_task_classifyapp.py", line 569, in switch
    main(argv)
  File "train_task_classifyapp.py", line 558, in main
    dense_layer_size, print_summary, num_epochs, batch_size)
  File "train_task_classifyapp.py", line 429, in evaluate
    epochs=num_epochs)
  File "train_task_classifyapp.py", line 243, in train_gen
    shuffle=True, callbacks=[checkpoint])
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 211, in fit_generator
    max_queue_size=max_queue_size)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/engine/training.py", line 1480, in evaluate_generator
    verbose=verbose)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/engine/training_generator.py", line 309, in evaluate_generator
    generator_output = next(output_generator)
  File "/home/vtelepov/tmp/env/lib/python3.6/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: GraphDef cannot be larger than 2GB.

**Comment by tbennun** [comment]
Which files are you using to train classifyapp?
