### ISSUE TITLE
Expected combineable dataset

### ISSUE THREAD

**Issue by s1530129650** [spcl/ncc#30]
I download tensorflow from https://polybox.ethz.ch/index.php/s/ojd0RPFOtUTPPRr and put tensorflow/ir_0 in data/.
When i run `python train_inst2vec.py`, there is a error :
"Expected combineable dataset"

I know the except is from https://github.com/spcl/ncc/blob/master/inst2vec/inst2vec_embedding.py#L56. However, I don't know why single file is not allowed? I just would like to quickly run the code and get some result, so i put a single file in /data.
Please tell me why it is wrong to put a single file in /data

error info

python-BaseException
Traceback (most recent call last):
  File "3\envs\ncc\lib\site-packages\absl\app.py", line 274, in run
    _run_main(main, args)
  File "\Anaconda3\envs\ncc\lib\site-packages\absl\app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/ncc/train_inst2vec.py", line 60, in main
    embedding_matrix, embeddings_file = i2v_emb.train_embeddings(data_folder, data_folders)
  File "\ncc\inst2vec\inst2vec_embedding.py", line 453, in train_embeddings
    data_pair_files = get_data_pair_files(data_folders, context_width)
  File "\ncc\inst2vec\inst2vec_embedding.py", line 56, in get_data_pair_files
    assert len(folders) > 1, "Expected combineable dataset"
AssertionError: Expected combineable dataset

Process finished with exit code 1

**Comment by tbennun** [comment]
@s1530129650 That should be fine. Does anything strange happen if you comment out that line?
